### ISSUE TITLE
ML - Bikin Model

### ISSUE THREAD

**Issue by ajimaulana123** [ajimaulana123/HOFE-hoax-detection-for-everyone#2]
### Week 2
**11 - 18 Nov 2024**

Deksripsi:

- **Bikin** model sesuai dataset.
- Pilih algoritma yang **sesuai** dengan dataset, jika **berlabel** pake **supervisered** , jika tidak **unsupervisered**

**Comment by zalaamxdawila** [comment]
Senang bisa bekerja sama, ini menjadi pengalaman yang sangat berkesan.
